FROM node:18-alpine

WORKDIR /app

COPY package.json ./

RUN npm install

COPY . .

ARG PORT
ARG ENV
ARG DATABASE_USER
ARG DATABASE_HOST
ARG DATABASE_NAME
ARG DATABASE_PASSWORD
ARG DATABASE_PORT
ARG JWT_SECRET

ENV PORT=$PORT
ENV ENV=$ENV
ENV DATABASE_USER=$DATABASE_USER
ENV DATABASE_HOST=$DATABASE_HOST
ENV DATABASE_NAME=$DATABASE_NAME
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD
ENV DATABASE_PORT=$DATABASE_PORT
ENV JWT_SECRET=$JWT_SECRET

RUN echo "PORT=${PORT}" > .env
RUN echo "NODE_ENV=${NODE_ENV}" > .env
RUN echo "DATABASE_USER=${DATABASE_USER}" > .env
RUN echo "DATABASE_HOST=${DATABASE_HOST}" > .env
RUN echo "DATABASE_NAME=${DATABASE_NAME}" > .env
RUN echo "DATABASE_PASSWORD=${DATABASE_PASSWORD}" > .env
RUN echo "DATABASE_PORT=${DATABASE_PORT}" > .env
RUN echo "JWT_SECRET=${JWT_SECRET}" > .env

RUN npm run build

EXPOSE 3000

CMD ["node", "build/server"]